spring.application.name=MSME_Fraud_Detection

# Database Configuration
spring.datasource.url=jdbc:h2:mem:msmedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password1

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console

# (OPTIONAL) Security - remove if not needed
spring.security.user.name=admin
spring.security.user.password={noop}12345